import Head from 'next/head';

//COMPONENTS
import Menu from '../components/Menu';

//CSS
import '../styles/globals.css';
import styles from '../styles/Correction.module.scss';

function MyApp({ Component, pageProps }) {
  return (
    <>
        <Head>
          <title>E.R.S - Portfólio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700;900&family=Open+Sans:wght@300;400;500;600;700;800&family=Playfair+Display:wght@700&display=swap" rel="stylesheet" />
        </Head>
        <Menu />
        <div className={styles.aligner}>
          <Component {...pageProps} />
        </div>
    </>
  )
}

export default MyApp
